### ISSUE TITLE
【第五章】Google Colaboratoryで動かすとエラーが出る

### ISSUE THREAD

**Issue by onozuka777** [makaishi2/pytorch_book_info#11]
第５章のなのですが、自宅のCPUのマシンではエラーが出ないのですが、Google ColaboratoryをGPUを用いて使うと以下の箇所でエラーがでます。

##### 損失値計算用にlabels変数を(N,1)次元の行列に変換する

labels1 = labels.view((-1, 1))

###### 次元数確認
print(labels1.shape)
###### 予測計算

outputs = net(inputs)
（以下エラー）

RuntimeError                              Traceback (most recent call last)
[<ipython-input-30-eb0bb14af298>](https://localhost:8080/#) in <module>
      1 # 予測計算
      2 
----> 3 outputs = net(inputs)

3 frames
[/usr/local/lib/python3.8/dist-packages/torch/nn/modules/linear.py](https://localhost:8080/#) in forward(self, input)
    112 
    113     def forward(self, input: Tensor) -> Tensor:
--> 114         return F.linear(input, self.weight, self.bias)
    115 
    116     def extra_repr(self) -> str:

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat1 in method wrapper_addmm)

これが何が悪いのかがわかりませんでした。
お手数をおかけしますが、ご教示いただけますでしょうか。
何卒、よろしくお願い申し上げます。

**Comment by makaishi2** [comment]
メッセージから、ランタイムをGPUで5章のnotebookを実行しているのではと推測されます。
 PyTorchがTensorFlowと比較するとGPUを利用するためのお作法がややこしいです。そのため、本書では、性能的に GPUが必要になる8章までは、すべてCPUで動かすことを前提とした実装コードになっています。
 メニューから「ランタイム」「ランタイムのタイプを変更」を選ぶと、現在どのランタイムになっているかわかりますので、GPUになっている場合はNoneに変更してカーネル再起動→再実行をしてみてください。

**Comment by onozuka777** [comment]
赤石先生

ご回答いただき、ありがとうございます。
そうなのですね。まだまだ勉強不足です。
実はこの本を冬休みの課題図書に自分に課しました。
ありがとうございます。
closeにいたします。
何卒、よろしくお願い申し上げます。

2022年12月24日(土) 22:40 Masanori Akaishi ***@***.***>:

**Comment by makaishi2** [comment]
ありがとうございます。
closeさせていただきます。
引き続きよろしくお願いいたします。
