### ISSUE TITLE
listの中に特定の数字が含まれないとcuda errorになる

### ISSUE THREAD

**Issue by sota1111** [makaishi2/pytorch_book_info#12]
n_output = len(set(list(labels.data.numpy())))
上記コードの実行結果が9になることがある。
このとき、以下のようなcudaエラーが発生する。
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE
数十回に一度なので、原因を見つけるのが苦労しましたorz

**Comment by makaishi2** [comment]
報告いただきありがとうございます。また、書き込みを見落としていたため、対応に時間がかかった点をお詫びいたします。

報告にはページの記載がなかったのですが、p.303のコード8-22とp.358のコード9-21の2カ所が該当しています。
いずれも、普段は起きないのですが、確率的にごく稀にこのような事象が発生しうる実装になっていました。
(机上計算した発生確率から恐らく9章の方で発生した事象を報告いただいたものと想像しています。)
該当する2カ所については、絶対このようなことが発生しないコードに差し替えました。

今後もこのような事象があった場合は、報告いただけると助かります。
よろしくお願いいたします。
