### ISSUE TITLE
p247 L12 と図のy軸ラベル

### ISSUE THREAD

**Issue by caq05630** [makaishi2/pytorch_book_info#14]
plt.ylabel("petal_length") -> plt.ylabel("petal_width") でその下の図のy軸もpetal_widthでは？

**Comment by caq05630** [comment]
ついでに
plt.xlabel("sepal_length") -> plt.xlabel("petal_length") かと

**Comment by caq05630** [comment]
これにともない、P247下から二行目も
  sepal_length -> petal_width
  petal_length -> petal_width
(横軸、縦軸の順序と想定して）

**Comment by makaishi2** [comment]
コメントいただきありがとうございます。
まず、紙面およびサンプルコード中で、アイリス・データセットの項目名の説明が一切なかったため、混乱を招いた点をお詫びいたします。
この点については[FAQ](https://github.com/makaishi2/pytorch_book_info/blob/main/refs/faqs.md)に記載しました。

確認してみましたが、結論として紙面の記載は正しいです。
今回のようにscikit-learnのライブラリを用いてアイリス・データセットを読み込んだ際の、項目名とデータの対応は、例えば次のようにfeauure_names属性をprintすることでわかります。

```
print(iris.feature_names)
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
```

このあとで

```
x_select = x_org[:,[0,2]]
```

によって、項目を４つから２つに絞り込んでいます。この際、残されるのは0列と2列に該当する「sepal length」と「petal length」です。
よって現状の紙面と正しく対応付いていることになります。

**Comment by makaishi2** [comment]
回答済み

**Comment by caq05630** [comment]
大変失礼いたしました。本書全部読み込み、色々と勉強させていただきました。有り難うございます。凄くステップby ステップでわかりやすいです。
