### ISSUE TITLE
p214 最終行からP215最初の行及びp215の図に関して

### ISSUE THREAD

**Issue by caq05630** [makaishi2/pytorch_book_info#15]
plt.xlabel('sepal_length') -> plt.xlabel('petal_length') 
plt.ylabel('sepal_length') -> plt.ylabel('petal_length') 

 p215の図のx, yラベルも上記かと思われます

**Comment by makaishi2** [comment]
コメントいただきありがとうございます。
まず、紙面およびサンプルコード中で、アイリス・データセットの項目名の説明が一切なかったため、混乱を招いた点をお詫びいたします。この点については[FAQ](https://github.com/makaishi2/pytorch_book_info/blob/main/refs/faqs.md)に記載しました。

確認してみましたが、結論として紙面の記載は正しいです。
今回のようにscikit-learnのライブラリを用いてアイリス・データセットを読み込んだ際の、項目名とデータの対応は、例えば次のようにfeauure_names属性をprintすることでわかります。

```
print(iris.feature_names)
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
```

このあとで

```
x_data = iris.data[:100,:2]
```

によって、項目を４つから２つに絞り込んでいます。この際、残されるのは0列と1列に該当する「sepal length」と「sepal width」です。
よって現状の紙面と正しく対応付いていることになります。

**Comment by caq05630** [comment]
大変失礼いたしました。本書全部読み込み、色々と勉強させていただきました。有り難うございます。凄くステップby ステップでわかりやすいです
