### ISSUE TITLE
第5章の重回帰が動かなくなりました

### ISSUE THREAD

**Issue by onozuka777** [makaishi2/pytorch_book_info#17]
以前は動いていたのですが、pytorchのバージョンを変えたからか、第５章以降のプログラムが同じエラーメッセージで動かなくなりました。
pytorchのバージョンは1.12.1 Pythonのバージョンは3.8.15です。
該当のコード
`
# 予測計算

outputs = net(inputs)

`
エラーメッセージは次の通りです。
RuntimeError                              Traceback (most recent call last)
セル41 を c:\Users\akira\Documents\Python\PyTorch深層学習プログラミング\pytorch_book_info-main\notebooks\ch05_regression.ipynb in <cell line: 3>()
      [1](vscode-notebook-cell:/c%3A/Users/akira/Documents/Python/PyTorch%E6%B7%B1%E5%B1%A4%E5%AD%A6%E7%BF%92%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%9F%E3%83%B3%E3%82%B0/pytorch_book_info-main/notebooks/ch05_regression.ipynb#X55sZmlsZQ%3D%3D?line=0) # 予測計算
----> [3](vscode-notebook-cell:/c%3A/Users/akira/Documents/Python/PyTorch%E6%B7%B1%E5%B1%A4%E5%AD%A6%E7%BF%92%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%9F%E3%83%B3%E3%82%B0/pytorch_book_info-main/notebooks/ch05_regression.ipynb#X55sZmlsZQ%3D%3D?line=2) outputs = net(inputs)

File c:\Anaconda3\envs\venv\lib\site-packages\torch\nn\modules\module.py:1130, in Module._call_impl(self, *input, **kwargs)
   1126 # If we don't have any hooks, we want to skip the rest of the logic in
   1127 # this function, and just call forward.
   1128 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1129         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130     return forward_call(*input, **kwargs)
   1131 # Do not call functions when jit is used
   1132 full_backward_hooks, non_full_backward_hooks = [], []

セル41 を c:\Users\akira\Documents\Python\PyTorch深層学習プログラミング\pytorch_book_info-main\notebooks\ch05_regression.ipynb in Net.forward(self, x)
     [17](vscode-notebook-cell:/c%3A/Users/akira/Documents/Python/PyTorch%E6%B7%B1%E5%B1%A4%E5%AD%A6%E7%BF%92%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%9F%E3%83%B3%E3%82%B0/pytorch_book_info-main/notebooks/ch05_regression.ipynb#X55sZmlsZQ%3D%3D?line=16) def forward(self, x):
---> [18](vscode-notebook-cell:/c%3A/Users/akira/Documents/Python/PyTorch%E6%B7%B1%E5%B1%A4%E5%AD%A6%E7%BF%92%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%9F%E3%83%B3%E3%82%B0/pytorch_book_info-main/notebooks/ch05_regression.ipynb#X55sZmlsZQ%3D%3D?line=17)     x1 = self.l1(x) # 線形回帰
     [19](vscode-notebook-cell:/c%3A/Users/akira/Documents/Python/PyTorch%E6%B7%B1%E5%B1%A4%E5%AD%A6%E7%BF%92%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%9F%E3%83%B3%E3%82%B0/pytorch_book_info-main/notebooks/ch05_regression.ipynb#X55sZmlsZQ%3D%3D?line=18)     return x1

File c:\Anaconda3\envs\venv\lib\site-packages\torch\nn\modules\module.py:1130, in Module._call_impl(self, *input, **kwargs)
   1126 # If we don't have any hooks, we want to skip the rest of the logic in
   1127 # this function, and just call forward.
   1128 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1129         or _global_forward_hooks or _global_forward_pre_hooks):
...
File c:\Anaconda3\envs\venv\lib\site-packages\torch\nn\modules\linear.py:114, in Linear.forward(self, input)
    113 def forward(self, input: Tensor) -> Tensor:
--> 114     return F.linear(input, self.weight, self.bias)

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat1 in method wrapper_addmm)

何が原因か種々ググったのですが、わからず、何が原因か、ご教示いただくことは可能でしょうか。

**Comment by makaishi2** [comment]
本書を丁寧にお読みいただき、ありがとうございます。

ご質問の件ですが、メッセージからローカルのAnaconda環境で動かしていると想像しました。
PyTorchのようなディープラーニング開発環境は、環境構築が極めて難しいです。
また、トラブルが起きた場合の問題判別が難しくなるので、あまり経験のない読者には、よほど特殊な事情がない限りGoogle Colabでプログラムを動かしていただくことをお勧めします。

以下については、参考情報としてお伝えします。

* 2023年4月8日時点で、Google Colabで5章のプログラムを動かしたところ、特に問題なく動作しました
* Google Colabで5章のプログラムを読み込んだ直後にランタイムをNone -> GPUに変更して実行したところ、ご質問いただいたのとほぼ同じエラーが発生しました。メッセージからも、GPU環境で動かない5章のプログラムをむりやりGPUありの環境で動かそうとしたため起きた問題なのではないかと想像されます。

ちなみに本書では、GPUは8章ではじめて利用する形になっています。
GPU利用時の注意点はここで詳しく説明しています。
Google Colabで実行していただき、本書の例題を最初の章から順番にお読みいただければ、GPU利用に伴うトラブルはほとんど起きないと思います。

**Comment by onozuka777** [comment]
ご回答、ありがとうございます。ひょっとしたら、同じような質問を以前したことがあるかもしれません。すみません。GPUを認識するようにPCをセットアップしているので、もし、よろしければ、全編GPU版のコードがあるととても助かります。コードの問題ではなく、きちんとテキストにもGPUについては８章以降と書いてあるのに、見落としてすみませんでした。

**Comment by makaishi2** [comment]
このような質問をする場合の基本的なルールとして、自分が「どのような環境で動かしているのか」を必ず記載するようにして下さい。
特に今回の場合は、「環境情報」がトラブルの本質だったわけで、その前提を書かずに質問をするのはルール違反です。
今回の最初の質問の仕方だと、Google Colabでもこの問題が起きるように他の読者が誤解を持つ可能性があります。
そのような情報がネットに出ることは著書としても困ることになるので、今後はこういう点にもご配慮いただけるとありがたいです。

今回の場合、書籍で想定している以外の利用方法で発生した問題への質問であり、その時点で著者としても本来は質問に回答する義務はありません。
以下は、ChatGPTに教えてもらった方法で、動作未検証なのであくまで「参考情報」です。

環境変数CUDA_VISIBLE_DEVICESを設定する

Windowsの場合：set CUDA_VISIBLE_DEVICES=""
Linux/MacOSの場合：export CUDA_VISIBLE_DEVICES=""

または

```
import torch
device = torch.device('cpu')
```
