### ISSUE TITLE
誤植：第1版第1刷P.85

### ISSUE THREAD

**Issue by kim-kic** [makaishi2/pytorch_book_info#18]
@makaishi2 様
第1版第1刷P.85の10行目と11行目の「指数関数」ですが、正しくは「べき関数」ではないでしょうか。

・指数関数（exponential function）は指数が変数
・べき関数（power function）は底が変数

ご確認いただけますと幸いです。

**Comment by makaishi2** [comment]
コメントいただきありがとうございます。
ご指摘のとおりで、本書の文脈では「べき関数」が正しい用語でした。
正誤訂正に反映させていただいています。
今後も何かありましたら、よろしくお願いいたします。
