### ISSUE TITLE
誤植？

### ISSUE THREAD

**Issue by nephrologist** [makaishi2/pytorch_book_info#2]
とても楽しく読ませてもらっています。
本の5章、2次元の回帰の説明のところ(手元ではkindle版でp.193)で

本
from torchsummary import summary
Notebook
from torchinfo import summary

となっておりました。ご存知かもしれないですが、一応ご報告です。

**Comment by makaishi2** [comment]
@nephrologist 様、
本書を詳しくお読みいただき、ありがとうございます。
また、今回の件に関してご報告いただき感謝しております。

ご指摘の箇所、誤植になりますので、正誤訂正に記載させていただきました。

https://github.com/makaishi2/pytorch_book_info/blob/main/refs/errors.md

今後も不明点がありましたら、同様にご報告いただけると大変助かります。
引き続きよろしくお願いいたします。
