### ISSUE TITLE
p.545のtotalについて

### ISSUE THREAD

**Issue by takishim** [makaishi2/pytorch_book_info#21]
1版1刷のp.545のtotalがlen(n21)になっていますが、len(yt)かlen(yp)の間違いではないでしょうか？

**Comment by makaishi2** [comment]
ご指摘いただき、ありがとうございます。
まったくご指摘のとおりで、変数n21はnotebookのずっと上の方で定義されているので参照エラーにはならないものの、値が3であるため、精度の計算結果が3.0という謎の値になっていました。notebookともども、正しくytに修正をかけました。
今後もよろしくお願いいたします。

(参考リンク)
講座2 notebook
https://github.com/makaishi2/pytorch_book_info/blob/main/notebooks/l02_numpy.ipynb

正誤訂正
https://github.com/makaishi2/pytorch_book_info/blob/main/refs/errors.md
