### ISSUE TITLE
p.254-255のoutputsについて

### ISSUE THREAD

**Issue by takishim** [makaishi2/pytorch_book_info#22]
1版1刷のp.254-255のoutputsについて、(PyTorchの実装がそうなっているんだと思いますが)行内のすべての列が同じ値になっており、maxを取っても実質的には意味がないように見えます。
(indicesもすべて0になっています)

**Comment by makaishi2** [comment]
ご指摘いただきありがとうございます。
この時点のoutputsの値は初期状態で、max関数の挙動の説明に使うのに適切でなかったです。
max関数説明用に一時的にoutputsの値を変更する方針で対応しました。
サンプルコードを修正し、正誤訂正に変更点を記載しました。
変更点をご確認いただければと思います。
引き続きよろしくお願いいたします。

(参考リンク)
7章notebook
https://github.com/makaishi2/pytorch_book_info/blob/main/notebooks/ch07_multi_classifier.ipynb

正誤訂正
https://github.com/makaishi2/pytorch_book_info/blob/main/refs/errors.md
