### ISSUE TITLE
多値分類のコードの書き方について

### ISSUE THREAD

**Issue by AsahiSuzuki** [makaishi2/pytorch_book_info#3]
お世話になります。現在、本書を参考に機械学習を勉強しています。
12章を元に6クラスの分類を試みているのですが、画像を表示する際、学習する際に、
UnidentifiedImageError: cannot identify image file
と表示されます。
２値分類と多値分類で変えるべき部分、画像を用意する際に気を付ける事についてご教授いただけますでしょうか。

**Comment by makaishi2** [comment]
ご質問いただきありがとうございます。
実装コードと、どこでエラーが起きているかを連携いただくことは可能でしょうか？

**Comment by AsahiSuzuki** [comment]
返信いただきありがとうございます。以下が実装コードのリンクになります。
[https://colab.research.google.com/drive/1VXt9iLs6xmEL28qC4en2R5bXXxAfbIrs?usp=sharing](url)
コード中の、「1ファインチューニング版」の学習まで実行しました。
ここまでで3つエラーが出ました。
長くなってしまい申し訳ありません。
お忙しいところ恐れ入りますがよろしくお願いいたします。
### **1.検証データを表示させる際のエラーログ**
<details>
UnidentifiedImageError                    Traceback (most recent call last)
<ipython-input-15-c1b47d9d2082> in <module>()
      5 for i in range(10):
      6     ax = plt.subplot(2, 10, i + 1)
----> 7     image, label = test_data[i]
      8     img = (np.transpose(image.numpy(), (1, 2, 0)) + 1)/2
      9     plt.imshow(img)

3 frames
/usr/local/lib/python3.7/dist-packages/torchvision/datasets/folder.py in __getitem__(self, index)
    230         """
    231         path, target = self.samples[index]
--> 232         sample = self.loader(path)
    233         if self.transform is not None:
    234             sample = self.transform(sample)

/usr/local/lib/python3.7/dist-packages/torchvision/datasets/folder.py in default_loader(path)
    267         return accimage_loader(path)
    268     else:
--> 269         return pil_loader(path)
    270 
    271 

/usr/local/lib/python3.7/dist-packages/torchvision/datasets/folder.py in pil_loader(path)
    248     # open path as file to avoid ResourceWarning (https://github.com/python-pillow/Pillow/issues/835)
    249     with open(path, 'rb') as f:
--> 250         img = Image.open(f)
    251         return img.convert('RGB')
    252 

/usr/local/lib/python3.7/dist-packages/PIL/Image.py in open(fp, mode)
   2894         warnings.warn(message)
   2895     raise UnidentifiedImageError(
-> 2896         "cannot identify image file %r" % (filename if filename else fp)
   2897     )
   2898 

UnidentifiedImageError: cannot identify image file <_io.BufferedReader name='snow_1/test/compacted/._simari1.JPG'>
</details>

### **2.イメージ表示の際のエラーログ**
<details>
UnidentifiedImageError                    Traceback (most recent call last)
<ipython-input-17-c4c5842646aa> in <module>()
      1 # 検証用データ(50件)
      2 torch_seed()
----> 3 show_images_labels(test_loader2, classes, None, None)

8 frames
/content/pythonlibs/torch_lib1/__init__.py in show_images_labels(loader, classes, net, device)
    159 
    160     # DataLoaderから最初の1セットを取得する
--> 161     for images, labels in loader:
    162         break
    163     # 表示数は50個とバッチサイズのうち小さい方

/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py in __next__(self)
    519             if self._sampler_iter is None:
    520                 self._reset()
--> 521             data = self._next_data()
    522             self._num_yielded += 1
    523             if self._dataset_kind == _DatasetKind.Iterable and \

/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py in _next_data(self)
    559     def _next_data(self):
    560         index = self._next_index()  # may raise StopIteration
--> 561         data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
    562         if self._pin_memory:
    563             data = _utils.pin_memory.pin_memory(data)

/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py in fetch(self, possibly_batched_index)
     47     def fetch(self, possibly_batched_index):
     48         if self.auto_collation:
---> 49             data = [self.dataset[idx] for idx in possibly_batched_index]
     50         else:
     51             data = self.dataset[possibly_batched_index]

/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py in <listcomp>(.0)
     47     def fetch(self, possibly_batched_index):
     48         if self.auto_collation:
---> 49             data = [self.dataset[idx] for idx in possibly_batched_index]
     50         else:
     51             data = self.dataset[possibly_batched_index]

/usr/local/lib/python3.7/dist-packages/torchvision/datasets/folder.py in __getitem__(self, index)
    230         """
    231         path, target = self.samples[index]
--> 232         sample = self.loader(path)
    233         if self.transform is not None:
    234             sample = self.transform(sample)

/usr/local/lib/python3.7/dist-packages/torchvision/datasets/folder.py in default_loader(path)
    267         return accimage_loader(path)
    268     else:
--> 269         return pil_loader(path)
    270 
    271 

/usr/local/lib/python3.7/dist-packages/torchvision/datasets/folder.py in pil_loader(path)
    248     # open path as file to avoid ResourceWarning (https://github.com/python-pillow/Pillow/issues/835)
    249     with open(path, 'rb') as f:
--> 250         img = Image.open(f)
    251         return img.convert('RGB')
    252 

/usr/local/lib/python3.7/dist-packages/PIL/Image.py in open(fp, mode)
   2894         warnings.warn(message)
   2895     raise UnidentifiedImageError(
-> 2896         "cannot identify image file %r" % (filename if filename else fp)
   2897     )
   2898 

UnidentifiedImageError: cannot identify image file <_io.BufferedReader name='snow_1/test/compacted/._simari28.JPG'>
</details>

### **3.ファインチューニング版で学習する際のエラーログ**
<details>
100%
24/24 [04:43<00:00, 11.70s/it]
---------------------------------------------------------------------------
UnidentifiedImageError                    Traceback (most recent call last)
<ipython-input-19-58fb103bdb92> in <module>()
      2 num_epochs = 5
      3 history = fit(net, optimizer, criterion, num_epochs, 
----> 4           train_loader, test_loader, device, history)

8 frames
/content/pythonlibs/torch_lib1/__init__.py in fit(net, optimizer, criterion, num_epochs, train_loader, test_loader, device, history)
     90         count = 0
     91 
---> 92         for inputs, labels in test_loader:
     93             count += len(labels)
     94 

/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py in __next__(self)
    519             if self._sampler_iter is None:
    520                 self._reset()
--> 521             data = self._next_data()
    522             self._num_yielded += 1
    523             if self._dataset_kind == _DatasetKind.Iterable and \

/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py in _next_data(self)
    559     def _next_data(self):
    560         index = self._next_index()  # may raise StopIteration
--> 561         data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
    562         if self._pin_memory:
    563             data = _utils.pin_memory.pin_memory(data)

/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py in fetch(self, possibly_batched_index)
     47     def fetch(self, possibly_batched_index):
     48         if self.auto_collation:
---> 49             data = [self.dataset[idx] for idx in possibly_batched_index]
     50         else:
     51             data = self.dataset[possibly_batched_index]

/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py in <listcomp>(.0)
     47     def fetch(self, possibly_batched_index):
     48         if self.auto_collation:
---> 49             data = [self.dataset[idx] for idx in possibly_batched_index]
     50         else:
     51             data = self.dataset[possibly_batched_index]

/usr/local/lib/python3.7/dist-packages/torchvision/datasets/folder.py in __getitem__(self, index)
    230         """
    231         path, target = self.samples[index]
--> 232         sample = self.loader(path)
    233         if self.transform is not None:
    234             sample = self.transform(sample)

/usr/local/lib/python3.7/dist-packages/torchvision/datasets/folder.py in default_loader(path)
    267         return accimage_loader(path)
    268     else:
--> 269         return pil_loader(path)
    270 
    271 

/usr/local/lib/python3.7/dist-packages/torchvision/datasets/folder.py in pil_loader(path)
    248     # open path as file to avoid ResourceWarning (https://github.com/python-pillow/Pillow/issues/835)
    249     with open(path, 'rb') as f:
--> 250         img = Image.open(f)
    251         return img.convert('RGB')
    252 

/usr/local/lib/python3.7/dist-packages/PIL/Image.py in open(fp, mode)
   2894         warnings.warn(message)
   2895     raise UnidentifiedImageError(
-> 2896         "cannot identify image file %r" % (filename if filename else fp)
   2897     )
   2898 

UnidentifiedImageError: cannot identify image file <_io.BufferedReader name='snow_1/test/compacted/._simari1.JPG'>
</details>

**Comment by makaishi2** [comment]
すみません、一番上の実装コードのリンクにアクセスできないです。

**Comment by AsahiSuzuki** [comment]
すみません。
https://colab.research.google.com/drive/1VXt9iLs6xmEL28qC4en2R5bXXxAfbIrs?usp=sharing
こちらのリンクからアクセスできますでしょうか。

**Comment by makaishi2** [comment]
エラーを起こしているのは、下記のファイルのあたりで、「.」から始まっているファイル名というのが気持ち悪そうです。

> snow_1/test/depth/._simo1.JPG  

ついでに

> snow_1/train/._.DS_Store  
> snow_1/train/.DS_Store  

というゴミファイルがあるあたりも気持ち悪いですね。
このあたりの気持ち悪いファイルの名前を直したり、消したりしてzipファイルをきれいな状態にするとどうなるでしょうか？

**Comment by AsahiSuzuki** [comment]
該当ファイルを削除したところ、エラーなく実行できました。
ご丁寧にありがとうございました。

**Comment by makaishi2** [comment]
うまくいってよかったです。
この実装コード、理屈の上では多値分類でもいけるつもりだったのですが、自分でも試したことがなかったので、その確認を取っていただけたのはありがたかったです。
今後も書籍の内容でわかりにくい点があれば、ご質問いただけると幸いです。
