### ISSUE TITLE
線形関数の図におけるweightの行数と列数について

### ISSUE THREAD

**Issue by sunggik** [makaishi2/pytorch_book_info#6]
@makaishi2 様

はじめまして。

この度、こちらの書籍を楽しく読ませて頂きました。高評価のレビューを読んでの購入でしたが、
実際に大変わかりやすく、本当に素晴らしい入門書だと感じました。

さて、表題の件ですが、書籍の図の中で、線形関数のweightの行数と列数の表記が、
全体として整合性が取れていないのではないかと思いましたので、ご報告いたしました。

具体的には、入力ベクトルのサイズ値に、weightの「行数」が対応する図（図4-3など）が
ある一方で、「列数」が対応する図（図7-1など）もございました。

（こちら、後者は線形関数のインスタンス変数としての形状を反映したものでしょうか。
Linearクラスのドキュメントを見ますと、線形関数は、保持している行列の「転置」を
入力に対して右から掛けるとの記載があり、紛らわしいと思いました。）

以上、ご確認いただけますと幸いです。

**Comment by makaishi2** [comment]
拙著をお読みいただき、ありがとうございます。
また、３件の正確な報告をいただき、大変感謝いたします。
いずれの指摘も、誤植に該当しましたので、すべて正誤訂正表に記載させていただきました。
引き続きよろしくお願いいたします。
