### ISSUE TITLE
誤植：P.439 コード11-8 summary関数の引数と出力結果

### ISSUE THREAD

**Issue by sunggik** [makaishi2/pytorch_book_info#8]
@makaishi2 様

P.439 コード11-8のsummary関数の引数ですが、入力サイズの箇所にバッチサイズの値が
ございませんでしたので、ご報告いたします。

こちら、書籍のまま入力したところエラーとなり、torchinfoのページを見て、バッチサイズも
必要なことを確認いたしました。この場合、出力も書籍と異なると考えております。
（コードは修正されていることをその後確認いたしました。）

どうぞよろしくお願いいたします。

**Comment by makaishi2** [comment]
ご指摘のとおり、こちらも誤植になります。
どうもありがとうございました。
